SELECT 
ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS TRIP_ID,
        idtrajet as old_id,
        vendorid,
        lpeppickupdatetime,
        lpepdropoffdatetime,
        passengercount,
        tripdistance,
        pulocationid,
        dolocationid,
        dropofflongitude,
        dropofflatitude,
        ratecodeid,
        storeandfwdflag,
        paymenttype,
        fareamount,
        extra,
        mtatax,
        improvementsurcharge,
        tipamount,
        tollsamount,
        ehailfee,
        totalamount,
        triptype,
        current_date() as load_date
FROM {{ source('taxi_nyc_data', 'taxi_trips') }}